// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID                string
	WhiteID           string
	BlackID           string
	Category          string
	BaseSeconds       int32
	IncrementSec      int32
	Status            string
	Result            pgtype.Text
	ResultReason      pgtype.Text
	Pgn               pgtype.Text
	WhiteRatingBefore pgtype.Int4
	WhiteRatingAfter  pgtype.Int4
	BlackRatingBefore pgtype.Int4
	BlackRatingAfter  pgtype.Int4
	StartedAt         pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	Voided            bool
}

type GameMessage struct {
	ID        int64
	GameID    string
	SenderID  string
	Body      string
	CreatedAt pgtype.Timestamptz
	Hidden    bool
}

type Rating struct {
	UserID      string
	Category    string
	Rating      int32
	GamesPlayed int32
}

type User struct {
	ID          string
	GoogleSub   string
	Email       string
	DisplayName string
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}
