// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AbortGame(ctx context.Context, arg AbortGameParams) error
	// Seed the three category rows at the default rating if absent.
	EnsureRatings(ctx context.Context, userID string) error
	FinishGame(ctx context.Context, arg FinishGameParams) error
	GamesForUser(ctx context.Context, arg GamesForUserParams) ([]Game, error)
	GetRating(ctx context.Context, arg GetRatingParams) (GetRatingRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	InsertActiveGame(ctx context.Context, arg InsertActiveGameParams) (string, error)
	Leaderboard(ctx context.Context, arg LeaderboardParams) ([]LeaderboardRow, error)
	ListRatings(ctx context.Context, userID string) ([]ListRatingsRow, error)
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
