// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortGame = `-- name: AbortGame :exec
UPDATE games
SET status = 'aborted',
    result = NULL,
    result_reason = $2,
    pgn = $3,
    ended_at = $4
WHERE id = $1
`

type AbortGameParams struct {
	ID           string
	ResultReason pgtype.Text
	Pgn          pgtype.Text
	EndedAt      pgtype.Timestamptz
}

func (q *Queries) AbortGame(ctx context.Context, arg AbortGameParams) error {
	_, err := q.db.Exec(ctx, abortGame,
		arg.ID,
		arg.ResultReason,
		arg.Pgn,
		arg.EndedAt,
	)
	return err
}

const ensureRatings = `-- name: EnsureRatings :exec
INSERT INTO ratings (user_id, category)
VALUES ($1, 'bullet'), ($1, 'blitz'), ($1, 'rapid')
ON CONFLICT (user_id, category) DO NOTHING
`

// Seed the three category rows at the default rating if absent.
func (q *Queries) EnsureRatings(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, ensureRatings, userID)
	return err
}

const finishGame = `-- name: FinishGame :exec
UPDATE games
SET status = 'finished',
    result = $2,
    result_reason = $3,
    pgn = $4,
    white_rating_before = $5,
    white_rating_after = $6,
    black_rating_before = $7,
    black_rating_after = $8,
    ended_at = $9
WHERE id = $1
`

type FinishGameParams struct {
	ID                string
	Result            pgtype.Text
	ResultReason      pgtype.Text
	Pgn               pgtype.Text
	WhiteRatingBefore pgtype.Int4
	WhiteRatingAfter  pgtype.Int4
	BlackRatingBefore pgtype.Int4
	BlackRatingAfter  pgtype.Int4
	EndedAt           pgtype.Timestamptz
}

func (q *Queries) FinishGame(ctx context.Context, arg FinishGameParams) error {
	_, err := q.db.Exec(ctx, finishGame,
		arg.ID,
		arg.Result,
		arg.ResultReason,
		arg.Pgn,
		arg.WhiteRatingBefore,
		arg.WhiteRatingAfter,
		arg.BlackRatingBefore,
		arg.BlackRatingAfter,
		arg.EndedAt,
	)
	return err
}

const gamesForUser = `-- name: GamesForUser :many
SELECT id, white_id, black_id, category, base_seconds, increment_sec, status, result, result_reason, pgn, white_rating_before, white_rating_after, black_rating_before, black_rating_after, started_at, ended_at
FROM games
WHERE (white_id = $1 OR black_id = $1) AND status = 'finished'
ORDER BY ended_at DESC
LIMIT $2
`

type GamesForUserParams struct {
	WhiteID string
	Limit   int32
}

func (q *Queries) GamesForUser(ctx context.Context, arg GamesForUserParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, gamesForUser, arg.WhiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhiteID,
			&i.BlackID,
			&i.Category,
			&i.BaseSeconds,
			&i.IncrementSec,
			&i.Status,
			&i.Result,
			&i.ResultReason,
			&i.Pgn,
			&i.WhiteRatingBefore,
			&i.WhiteRatingAfter,
			&i.BlackRatingBefore,
			&i.BlackRatingAfter,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRating = `-- name: GetRating :one
SELECT rating, games_played
FROM ratings
WHERE user_id = $1 AND category = $2
`

type GetRatingParams struct {
	UserID   string
	Category string
}

type GetRatingRow struct {
	Rating      int32
	GamesPlayed int32
}

func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (GetRatingRow, error) {
	row := q.db.QueryRow(ctx, getRating, arg.UserID, arg.Category)
	var i GetRatingRow
	err := row.Scan(&i.Rating, &i.GamesPlayed)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, google_sub, email, display_name, avatar_url, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertActiveGame = `-- name: InsertActiveGame :one
INSERT INTO games (white_id, black_id, category, base_seconds, increment_sec, status)
VALUES ($1, $2, $3, $4, $5, 'active')
RETURNING id
`

type InsertActiveGameParams struct {
	WhiteID      string
	BlackID      string
	Category     string
	BaseSeconds  int32
	IncrementSec int32
}

func (q *Queries) InsertActiveGame(ctx context.Context, arg InsertActiveGameParams) (string, error) {
	row := q.db.QueryRow(ctx, insertActiveGame,
		arg.WhiteID,
		arg.BlackID,
		arg.Category,
		arg.BaseSeconds,
		arg.IncrementSec,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const leaderboard = `-- name: Leaderboard :many
SELECT u.display_name, r.rating, r.games_played
FROM ratings r
JOIN users u ON u.id = r.user_id
WHERE r.category = $1
ORDER BY r.rating DESC, u.display_name ASC
LIMIT $2
`

type LeaderboardParams struct {
	Category string
	Limit    int32
}

type LeaderboardRow struct {
	DisplayName string
	Rating      int32
	GamesPlayed int32
}

func (q *Queries) Leaderboard(ctx context.Context, arg LeaderboardParams) ([]LeaderboardRow, error) {
	rows, err := q.db.Query(ctx, leaderboard, arg.Category, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardRow
	for rows.Next() {
		var i LeaderboardRow
		if err := rows.Scan(&i.DisplayName, &i.Rating, &i.GamesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatings = `-- name: ListRatings :many
SELECT category, rating, games_played
FROM ratings
WHERE user_id = $1
`

type ListRatingsRow struct {
	Category    string
	Rating      int32
	GamesPlayed int32
}

func (q *Queries) ListRatings(ctx context.Context, userID string) ([]ListRatingsRow, error) {
	rows, err := q.db.Query(ctx, listRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatingsRow
	for rows.Next() {
		var i ListRatingsRow
		if err := rows.Scan(&i.Category, &i.Rating, &i.GamesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users SET display_name = $2 WHERE id = $1 RETURNING id, google_sub, email, display_name, avatar_url, created_at
`

type UpdateDisplayNameParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateRating = `-- name: UpdateRating :exec
UPDATE ratings
SET rating = $3, games_played = games_played + 1
WHERE user_id = $1 AND category = $2
`

type UpdateRatingParams struct {
	UserID   string
	Category string
	Rating   int32
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) error {
	_, err := q.db.Exec(ctx, updateRating, arg.UserID, arg.Category, arg.Rating)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_sub, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_sub) DO UPDATE
SET email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url
RETURNING id, google_sub, email, display_name, avatar_url, created_at
`

type UpsertUserParams struct {
	GoogleSub   string
	Email       string
	DisplayName string
	AvatarUrl   pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleSub,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
