// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AbortGame(ctx context.Context, arg AbortGameParams) error
	AdminAllRatings(ctx context.Context) ([]Rating, error)
	AdminGameMessages(ctx context.Context, gameID string) ([]AdminGameMessagesRow, error)
	AdminGamesByUser(ctx context.Context, arg AdminGamesByUserParams) ([]AdminGamesByUserRow, error)
	AdminListGames(ctx context.Context, limit int32) ([]AdminListGamesRow, error)
	AdminListUsers(ctx context.Context, limit int32) ([]AdminListUsersRow, error)
	AdminSetGameVoided(ctx context.Context, arg AdminSetGameVoidedParams) error
	AdminSetMessageHidden(ctx context.Context, arg AdminSetMessageHiddenParams) error
	AdminSetRating(ctx context.Context, arg AdminSetRatingParams) error
	// Seed the three category rows at the default rating if absent.
	EnsureRatings(ctx context.Context, userID string) error
	FinishGame(ctx context.Context, arg FinishGameParams) error
	GameByID(ctx context.Context, id string) (Game, error)
	GameMessages(ctx context.Context, gameID string) ([]GameMessagesRow, error)
	GamesForUser(ctx context.Context, arg GamesForUserParams) ([]Game, error)
	GetRating(ctx context.Context, arg GetRatingParams) (GetRatingRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	InsertActiveGame(ctx context.Context, arg InsertActiveGameParams) (string, error)
	InsertGameMessage(ctx context.Context, arg InsertGameMessageParams) (InsertGameMessageRow, error)
	Leaderboard(ctx context.Context, arg LeaderboardParams) ([]LeaderboardRow, error)
	ListRatings(ctx context.Context, userID string) ([]ListRatingsRow, error)
	UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error)
	UpdateRating(ctx context.Context, arg UpdateRatingParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
